language: node_js
node_js:
  - "12"

services:
  - docker

script:
  - yarn build

deploy:
  provider: script
  script: bash scripts/publish_dockerhub.sh $TRAVIS_TAG
  on:
    tags: true
    all_branches: true
